services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=8 --threads=4 --timeout=180 --max-requests=1000 --max-requests-jitter=50
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: sodiq2005.py
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  celery:
    build: .
    command: celery -A config worker -l info --concurrency=4 -P solo
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - db
      - redis

volumes:
  pgdata:
