# Generated by Django 5.2.5 on 2025-09-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Umumiy ma'lumot"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Talaba'), ('teacher', "O'qituvchi"), ('admin', 'Admin')], default='student', max_length=50, verbose_name='Rol'),
        ),
    ]
