# Generated by Django 5.2.5 on 2025-09-03 10:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_subject_description_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='full_html_file',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="To'liq matn (HTML)"),
        ),
    ]
