# Generated by Django 5.2.5 on 2025-09-03 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_theme_full_html_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='full_html_file',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="To'liq matn (HTML)"),
        ),
    ]
