# Generated by Django 5.2.5 on 2025-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_theme_full_html_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
