# Generated by Django 5.2.5 on 2025-09-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainApp', '0006_user_average_score_user_total_attempts_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt'], name='mainApp_ans_attempt_26846e_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='mainApp_ans_questio_e90c73_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['selected_option'], name='mainApp_ans_selecte_4b1b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_correct'], name='mainApp_ans_is_corr_54bf1d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='mainApp_cat_name_1ca2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question'], name='mainApp_opt_questio_b9dab1_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['is_correct'], name='mainApp_opt_is_corr_e3952c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test'], name='mainApp_que_test_id_d92aef_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category'], name='mainApp_sub_categor_95bfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='mainApp_sub_name_a199cc_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['theme'], name='mainApp_tes_theme_i_dec07c_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['name'], name='mainApp_tes_name_d3e498_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user'], name='mainApp_tes_user_id_5665d5_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test'], name='mainApp_tes_test_id_1e1785_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['started_at'], name='mainApp_tes_started_926978_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['finished_at'], name='mainApp_tes_finishe_28a05a_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['score'], name='mainApp_tes_score_74fa85_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['subject'], name='mainApp_the_subject_172a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['name'], name='mainApp_the_name_3e3efa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='mainApp_use_role_d27460_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['group'], name='mainApp_use_group_i_b0fe0d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['average_score'], name='mainApp_use_average_4cb449_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['total_attempts'], name='mainApp_use_total_a_2a7f5b_idx'),
        ),
    ]
