# Generated by Django 5.2.5 on 2025-09-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_answer_mainapp_ans_attempt_26846e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='mainApp.group', verbose_name='Guruhlar'),
        ),
    ]
