# Generated by Django 5.2.5 on 2025-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainApp', '0008_subject_groups'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email', None), _negated=True), fields=('email',), name='unique_email_not_null'),
        ),
    ]
