# Generated by Django 5.2.5 on 2025-09-21 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0011_alter_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_id', models.CharField(max_length=100, verbose_name='Talaba ID')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Pasport raqami')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ismi')),
                ('more_info', models.JSONField(blank=True, default=dict)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_excel', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.group')),
            ],
        ),
    ]
