# Generated by Django 5.2.5 on 2025-09-21 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='imports/', verbose_name='Excel fayl')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.group', verbose_name='Guruh')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
