# Generated by Django 5.2.5 on 2025-09-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
        ('mainApp', '0011_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/', verbose_name='Excel fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.group', verbose_name='Guruh')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentExcel',
        ),
    ]
